---
apiVersion: v1
kind: Namespace
metadata:
  name: swagger

---
kind: Service
apiVersion: v1
metadata:
  name: swagger-ui
  namespace: swagger
spec:
  selector:
    app: swagger-ui
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: swagger-ui
  namespace: swagger
  labels:
    app: swagger-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swagger-ui
  template:
    metadata:
      labels:
        app: swagger-ui
    spec:
      containers:
      - name: swagger-ui
        image: swaggerapi/swagger-ui #build new image for adding local swaggerfile
        ports:
        - containerPort: 8080
        env:
        - name: BASE_URL
          value: /
        - name: API_URLS
          value: >-
            [
            {url:'http://kube-api.loc/openapi/v2',name:'kubernetes'}
            ]

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: swagger-ui-ingress
  namespace: swagger
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: swagger.loc
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: swagger-ui
            port:
              number: 80

